### ISSUE TITLE
关于使用CD,或者使用积分的问题

### ISSUE THREAD

**Issue by chanchancl** [HibiKier/nonebot_plugin_gamedraw#12]
我想对抽卡的使用次数进行一定的限制,
比如每个人,抽卡有10分钟的CD时间.

或者需要消耗某种积分,

当条件不满足时,则拒绝服务

我自己会写一点代码,该如何加入这个功能?

**Comment by HibiKier** [comment]
如果用积分的话需要写一套积分系统，存储消耗什么的，如果用cd的会简单一些。
给一个示例：
在__init__.py文件中：
class FreqLimiter:
    def __init__(self, default_cd_seconds):
        self.next_time = defaultdict(float)
        self.default_cd = default_cd_seconds

    def check(self, key) -> bool:
        return time.time() >= self.next_time[key]

    def start_cd(self, key, cd_time=0):
        self.next_time[key] = time.time() + (cd_time if cd_time > 0 else self.default_cd)

    def left_time(self, key) -> float:
        return self.next_time[key] - time.time()

_flmt = FreqLimiter(60)     # 60秒cd

@prts.handle()
async def _(bot: Bot, event: MessageEvent, state: T_State):
    if not _flmt.check(event.user_id):
        await prts.finsh('您的抽卡正在cd！')
    _flmt.start_cd(event.user_id)
    msg = str(event.get_message()).strip()
    if msg in ['方舟一井', '方舟1井']:
        num = 300
    else:
        rmsg = re.search(r'.*?方舟(.*)抽', msg)
        if rmsg:
            num, flag = check_num(rmsg.group(1), 300)
            if not flag:
                await prts.finish(num, at_sender=True)
        else:
            return
    await prts.send(await prts_draw(int(num)), at_sender=True)

**Comment by HibiKier** [comment]
如果用积分的话需要写一套积分系统，存储消耗什么的，如果用cd的会简单一些。
给一个示例：
在__init__.py文件中：
```Python
class FreqLimiter:
    def init(self, default_cd_seconds):
        self.next_time = defaultdict(float)
        self.default_cd = default_cd_seconds

    def check(self, key) -> bool:
        return time.time() >= self.next_time[key]

    def start_cd(self, key, cd_time=0):
        self.next_time[key] = time.time() + (cd_time if cd_time > 0 else self.default_cd)

_flmt = FreqLimiter(60) # 60秒cd


@prts.handle()
async def _(bot: Bot, event: MessageEvent, state: T_State):
    # 判断是否在cd
    if not _flmt.check(event.user_id):
        await prts.finish('您的抽卡正在cd！')
    # 开始cd
    _flmt.start_cd(event.user_id)
    msg = str(event.get_message()).strip()
    if msg in ['方舟一井', '方舟1井']:
        num = 300
    else:
        rmsg = re.search(r'.*?方舟(.*)抽', msg)
        if rmsg:
            num, flag = check_num(rmsg.group(1), 300)
            if not flag:
                await prts.finish(num, at_sender=True)
        else:
            return
    await prts.send(await prts_draw(int(num)), at_sender=True)
```

**Comment by HibiKier** [comment]
from collections import defaultdict

**Comment by HibiKier** [comment]
from collections import defaultdict
import time

**Comment by chanchancl** [comment]
感谢回答，我去尝试改动一下

我现在使用的是通过pip安装的插件
如果要修改插件的话，目前看有2个方法
1.直接修改pip安装的文件
2.把插件的源码clone到 plugin目录下，修改，然后加载本地的插件

你觉得这两种方法哪个更好呢？

**Comment by HibiKier** [comment]
clone会更好些，将来更新的话可能会覆盖掉你修改的内容，虽然将来也有可能会添加cd或积分什么的
