### ISSUE TITLE
无法发送图片

### ISSUE THREAD

**Issue by Logos23333** [HibiKier/nonebot_plugin_gamedraw#15]
![image](https://user-images.githubusercontent.com/26246545/135422176-168f76e4-184d-427c-b257-575feb7a6562.png)
nonebot端没报错
go-cqhttp端一直提示消息图片上传失败：upload failed

**Comment by Logos23333** [comment]
补充一下，现在发出来的消息是长这样的：
![}NLH$U05C1)EPBQ~KG(PKE1](https://user-images.githubusercontent.com/26246545/135572584-cadf2c43-1aa7-47fa-baae-24ca90d1be8c.png)

我看到有个pr和我现在的情况很像，也是发不出去图片，试过把"base64://"删掉，但是没有作用，图片还是发不出来。

**Comment by HibiKier** [comment]
不能把base64://删除的，生成的图片是以base64发送的，pr是把重复的base64://删除了，我本地可以正常发送图片，你目前是本地和服务器都无法发送图片吗？

**Comment by Logos23333** [comment]
> 不能把base64://删除的，生成的图片是以base64发送的，pr是把重复的base64://删除了，我本地可以正常发送图片，你目前是本地和服务器都无法发送图片吗？

本地是指？
bot的其它插件发送图片是正常的，只有这个抽卡的插件会提示upload failed

**Comment by HibiKier** [comment]
就是本地电脑啊，本地和服务器都是图片上传失败？我测试无法复现，可以正常发送图片

**Comment by Logos23333** [comment]
我重装了一遍环境，换了最新版的gocqhttp之后好了
![image](https://user-images.githubusercontent.com/26246545/135579968-325d9cfb-671a-4e5b-a89c-5223c7856a51.png)
