### ISSUE TITLE
原神卡池错误汇报

### ISSUE THREAD

**Issue by fourvolt69** [HibiKier/nonebot_plugin_gamedraw#24]
您好，在该插件使用过程中，我发现了3个原神卡池错误
1、原神2.3版本上半双卡池（阿贝多+优菈），2.4版本上半双卡池（魈+申鹤）下半双卡池（钟离+甘雨），双卡池之间保底共享。双卡池导致原神抽卡出现严重bug，当前池为荒泷一斗，暂时无法复现并截获日志。应多一个pool_name == 'char2'的分。
2、武器池保底为80（与角色和常驻的90保底不同）。文字说明和概率判断时应加if pool_name == 'arms'，保底为80，获取五星概率在62后提高。
3、武器池更新了神铸定轨功能，即玩家可以在本期两把up武器选择一个「定轨」，歪两次必获得「定轨」的武器，没歪则清空。可以理解为武器池也有两个小保底一个大保底，但更新下一个池子之后，保底不继承。

**Comment by HibiKier** [comment]
呃，如果双UP的话，就和方舟一样放一个池子里，如果抽到UP就让两个UP角色各站50%的概率

**Comment by fourvolt69** [comment]
> 呃，如果双UP的话，就和方舟一样放一个池子里，如果抽到UP就让两个UP角色各站50%的概率

实际是五星角色分开两个池子（角色祈愿-1和角色祈愿-2），顺带一提明天中午更新2.4版本，可以测bug了

**Comment by HibiKier** [comment]
目前来看UP是可以正常获取，只是判断时间的时候出了点问题，代码写的太烂了，目前打算全部重写项目，现在修复了日期判断并且提供了原神180抽大保底
