### ISSUE TITLE
明日方舟抽卡bug

### ISSUE THREAD

**Issue by MeetWq** [HibiKier/nonebot_plugin_gamedraw#41]
https://github.com/HibiKier/nonebot_plugin_gamedraw/blob/7a698baf6bad7901f58aacd59ce6e963968e1f21/draw_card/handles/prts_handle.py#L106-L116

绘图和显示结果用的卡牌列表不一致

**Comment by HibiKier** [comment]
[@pull/44](https://github.com/HibiKier/nonebot_plugin_gamedraw/pull/44)
