### ISSUE TITLE
明日方舟的卡池更新错误

### ISSUE THREAD

**Issue by yuyuziYYZ** [HibiKier/nonebot_plugin_gamedraw#50]
05-08 13:24:52 [SUCCESS] nonebot | ONEBOT V11 2133541714 | [message.group.normal]: Message 682552577 from 2674367570@[群:951834114] "重载方舟卡池"
05-08 13:24:52 [INFO] nonebot | Event will be handled by <Matcher from src.plugins.draw_card, type=message, priority=1, temp=False>
05-08 13:24:58 [WARNING] src | 明日方舟 重载UP池错误：<class 'IndexError'>：list index out of range
05-08 13:24:58 [INFO] nonebot | Matcher <Matcher from src.plugins.draw_card, type=message, priority=1, temp=False> running complete

**Comment by HibiKier** [comment]
可能是页面格式更改

**Comment by yuyuziYYZ** [comment]
> 可能是页面格式更改

那这个是要等插件更新嘛
