### ISSUE TITLE
背景颜色问题

### ISSUE THREAD

**Issue by kkchara** [HibiKier/nonebot_plugin_gamedraw#51]
原神和方舟角色没有对应颜色背景，是设计如此还是bug？

**Comment by kkchara** [comment]
![image](https://user-images.githubusercontent.com/80607663/168539514-ab6df4b8-ce3e-47d4-80df-c34b27dc508b.png)
![image](https://user-images.githubusercontent.com/80607663/168539559-2ccd7ea1-1fbc-431b-ad1b-3d64864fcd42.png)

**Comment by HibiKier** [comment]
更新的图片没有就是没有的
