### ISSUE TITLE
碧蓝航线和坎公骑冠剑获取的json为空

### ISSUE THREAD

**Issue by Falling-with** [HibiKier/nonebot_plugin_gamedraw#67]
/data/draw_card/下的azur.json和guardian.json都是空的

**Comment by Falling-with** [comment]
更新也没有用但提示更新成功

**Comment by mmmjie** [comment]
同样的问题

**Comment by NumberSir** [comment]
> /data/draw_card/下的azur.json和guardian.json都是空的

> 更新也没有用但提示更新成功

> 同样的问题

坎剑爱莫能助，但碧蓝航线的问题刚修完，出现问题是因为bwiki结构改动，见 #74
