### ISSUE TITLE
碧蓝档案和碧蓝航线抽卡失效

### ISSUE THREAD

**Issue by Death-Star-Glory** [HibiKier/nonebot_plugin_gamedraw#68]
碧蓝档案和碧蓝航线的数据库显示正常下载完成，但是在使用中，两者显示皆显示list index out of range报错

**Comment by gaytehub1** [comment]
_i met the same problem_

**Comment by NumberSir** [comment]
> 碧蓝档案和碧蓝航线的数据库显示正常下载完成，但是在使用中，两者显示皆显示list index out of range报错

> _i met the same problem_

碧蓝档案的错误是因为碧蓝档案wiki站点关了，要等什么时候重新开放才会好；
碧蓝航线的错误刚修完，是因为wiki结构改了，见 #74
