### ISSUE TITLE
启动时报错ModuleNotFoundError: No module named 'pypinyin'

### ISSUE THREAD

**Issue by yoiyami96** [HibiKier/nonebot_plugin_gamedraw#7]
如果是我的问题太弱智那抱歉打扰了
nonebot版本v2.0.0a12，python3.9，日志如下：
06-03 07:23:15 [ERROR] nonebot | Failed to import "nonebot_plugin_gamedraw"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb
.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nb_cli\handlers\deploy.py", line 17, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".\bot.py", line 23, in <module>
    nonebot.load_plugins("src/plugins")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\plugin\__init__.py", line 1013, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\plugin\__init__.py", line 960, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\plugin\manager.py", line 146, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\import
lib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "src/plugins\nonebot_plugin_gamedraw\__init__.py", line 5, in <module>
    from .genshin_handle import genshin_draw, update_genshin_info, reset_count
  File "src/plugins\nonebot_plugin_gamedraw\genshin_handle.py", line 5, in <modu
le>
    from .update_game_info import update_info
  File "src/plugins\nonebot_plugin_gamedraw\update_game_info.py", line 7, in <mo
dule>
    from .util import download_img
  File "src/plugins\nonebot_plugin_gamedraw\util.py", line 10, in <module>
    import pypinyin
ModuleNotFoundError: No module named 'pypinyin'

**Comment by HibiKier** [comment]
> 
> 
> 如果是我的问题太弱智那抱歉打扰了
> nonebot版本v2.0.0a12，python3.9，日志如下：
> 06-03 07:23:15 [ERROR] nonebot | Failed to import "nonebot_plugin_gamedraw"
> Traceback (most recent call last):
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> py", line 197, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb .exe__main__.py", line 7, in
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> ackages\click\core.py", line 829, in **call**
> return self.main(*args, **kwargs)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> ackages\click\core.py", line 782, in main
> rv = self.invoke(ctx)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> ackages\click\core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 610, in invoke return callback(*args, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\commands\main.py", line 26, in run run_bot(file, app) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\handlers\deploy.py", line 17, in run_bot module = importlib.import_module(module_name) File "c:\users\administrator\appdata\local\programs\python\python39\lib\import lib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1030, in _gcd_import
> File "", line 1007, in _find_and_load
> File "", line 986, in _find_and_load_unlocked
> File "", line 680, in _load_unlocked
> File "", line 790, in exec_module
> File "", line 228, in _call_with_frames_removed File ".\bot.py", line 23, in nonebot.load_plugins("src/plugins") File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nonebot\plugin__init__.py", line 1013, in load_plugins
> result = context.run(_load_plugin, manager, plugin_name)
> 
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\nonebot\plugin__init__.py", line 960, in _load_plugin
> > module = manager.load_plugin(plugin_name)
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\nonebot\plugin\manager.py", line 146, in load_plugin
> > return importlib.import_module(f"{self.namespace}.{name}")
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\import
> > lib__init__.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1030, in _gcd_import
> > File "", line 1007, in _find_and_load
> > File "", line 986, in _find_and_load_unlocked
> > File "", line 680, in _load_unlocked
> > File "", line 790, in exec_module
> > File "", line 228, in _call_with_frames_removed
> > File "src/plugins\nonebot_plugin_gamedraw__init__.py", line 5, in 
> > from .genshin_handle import genshin_draw, update_genshin_info, reset_count
> > File "src/plugins\nonebot_plugin_gamedraw\genshin_handle.py", line 5, in 
> > from .update_game_info import update_info
> > File "src/plugins\nonebot_plugin_gamedraw\update_game_info.py", line 7, in 
> > from .util import download_img
> > File "src/plugins\nonebot_plugin_gamedraw\util.py", line 10, in 
> > import pypinyin
> > ModuleNotFoundError: No module named 'pypinyin'

缺少pypinyin，直接pip install pypinyin

**Comment by yoiyami96** [comment]
> > 如果是我的问题太弱智那抱歉打扰了
> > nonebot版本v2.0.0a12，python3.9，日志如下：
> > 06-03 07:23:15 [ERROR] nonebot | Failed to import "nonebot_plugin_gamedraw"
> > Traceback (most recent call last):
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> > py", line 197, in _run_module_as_main
> > return _run_code(code, main_globals, None,
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> > py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb .exe__main__.py", line 7, in
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\click\core.py", line 829, in **call**
> > return self.main(*args, **kwargs)
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\click\core.py", line 782, in main
> > rv = self.invoke(ctx)
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\click\core.py", line 1259, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 610, in invoke return callback(*args, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\commands\main.py", line 26, in run run_bot(file, app) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\handlers\deploy.py", line 17, in run_bot module = importlib.import_module(module_name) File "c:\users\administrator\appdata\local\programs\python\python39\lib\import lib__init__.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1030, in _gcd_import
> > File "", line 1007, in _find_and_load
> > File "", line 986, in _find_and_load_unlocked
> > File "", line 680, in _load_unlocked
> > File "", line 790, in exec_module
> > File "", line 228, in _call_with_frames_removed File ".\bot.py", line 23, in nonebot.load_plugins("src/plugins") File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nonebot\plugin__init__.py", line 1013, in load_plugins
> > result = context.run(_load_plugin, manager, plugin_name)
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\nonebot\plugin__init__.py", line 960, in _load_plugin
> > > module = manager.load_plugin(plugin_name)
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\nonebot\plugin\manager.py", line 146, in load_plugin
> > > return importlib.import_module(f"{self.namespace}.{name}")
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\import
> > > lib__init__.py", line 127, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1030, in _gcd_import
> > > File "", line 1007, in _find_and_load
> > > File "", line 986, in _find_and_load_unlocked
> > > File "", line 680, in _load_unlocked
> > > File "", line 790, in exec_module
> > > File "", line 228, in _call_with_frames_removed
> > > File "src/plugins\nonebot_plugin_gamedraw__init__.py", line 5, in
> > > from .genshin_handle import genshin_draw, update_genshin_info, reset_count
> > > File "src/plugins\nonebot_plugin_gamedraw\genshin_handle.py", line 5, in
> > > from .update_game_info import update_info
> > > File "src/plugins\nonebot_plugin_gamedraw\update_game_info.py", line 7, in
> > > from .util import download_img
> > > File "src/plugins\nonebot_plugin_gamedraw\util.py", line 10, in
> > > import pypinyin
> > > ModuleNotFoundError: No module named 'pypinyin'
> 
> 缺少pypinyin，直接pip install pypinyin

草，真的是我弱智了，安装上pypinyin和ujson就好了，谢谢

**Comment by yoiyami96** [comment]
> > 如果是我的问题太弱智那抱歉打扰了
> > nonebot版本v2.0.0a12，python3.9，日志如下：
> > 06-03 07:23:15 [ERROR] nonebot | Failed to import "nonebot_plugin_gamedraw"
> > Traceback (most recent call last):
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> > py", line 197, in _run_module_as_main
> > return _run_code(code, main_globals, None,
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> > py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb .exe__main__.py", line 7, in
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\click\core.py", line 829, in **call**
> > return self.main(*args, **kwargs)
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\click\core.py", line 782, in main
> > rv = self.invoke(ctx)
> > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > ackages\click\core.py", line 1259, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 610, in invoke return callback(*args, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\commands\main.py", line 26, in run run_bot(file, app) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\handlers\deploy.py", line 17, in run_bot module = importlib.import_module(module_name) File "c:\users\administrator\appdata\local\programs\python\python39\lib\import lib__init__.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1030, in _gcd_import
> > File "", line 1007, in _find_and_load
> > File "", line 986, in _find_and_load_unlocked
> > File "", line 680, in _load_unlocked
> > File "", line 790, in exec_module
> > File "", line 228, in _call_with_frames_removed File ".\bot.py", line 23, in nonebot.load_plugins("src/plugins") File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nonebot\plugin__init__.py", line 1013, in load_plugins
> > result = context.run(_load_plugin, manager, plugin_name)
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\nonebot\plugin__init__.py", line 960, in _load_plugin
> > > module = manager.load_plugin(plugin_name)
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\nonebot\plugin\manager.py", line 146, in load_plugin
> > > return importlib.import_module(f"{self.namespace}.{name}")
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\import
> > > lib__init__.py", line 127, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1030, in _gcd_import
> > > File "", line 1007, in _find_and_load
> > > File "", line 986, in _find_and_load_unlocked
> > > File "", line 680, in _load_unlocked
> > > File "", line 790, in exec_module
> > > File "", line 228, in _call_with_frames_removed
> > > File "src/plugins\nonebot_plugin_gamedraw__init__.py", line 5, in
> > > from .genshin_handle import genshin_draw, update_genshin_info, reset_count
> > > File "src/plugins\nonebot_plugin_gamedraw\genshin_handle.py", line 5, in
> > > from .update_game_info import update_info
> > > File "src/plugins\nonebot_plugin_gamedraw\update_game_info.py", line 7, in
> > > from .util import download_img
> > > File "src/plugins\nonebot_plugin_gamedraw\util.py", line 10, in
> > > import pypinyin
> > > ModuleNotFoundError: No module named 'pypinyin'
> 
> 缺少pypinyin，直接pip install pypinyin

请问方舟抽卡只有新干员up池没有轮换池吗

**Comment by HibiKier** [comment]
> 
> 
> > > 如果是我的问题太弱智那抱歉打扰了
> > > nonebot版本v2.0.0a12，python3.9，日志如下：
> > > 06-03 07:23:15 [ERROR] nonebot | Failed to import "nonebot_plugin_gamedraw"
> > > Traceback (most recent call last):
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> > > py", line 197, in _run_module_as_main
> > > return _run_code(code, main_globals, None,
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
> > > py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb .exe__main__.py", line 7, in
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\click\core.py", line 829, in **call**
> > > return self.main(*args, **kwargs)
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\click\core.py", line 782, in main
> > > rv = self.invoke(ctx)
> > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > ackages\click\core.py", line 1259, in invoke
> > > return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\click\core.py", line 610, in invoke return callback(*args, **kwargs) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\commands\main.py", line 26, in run run_bot(file, app) File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nb_cli\handlers\deploy.py", line 17, in run_bot module = importlib.import_module(module_name) File "c:\users\administrator\appdata\local\programs\python\python39\lib\import lib__init__.py", line 127, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1030, in _gcd_import
> > > File "", line 1007, in _find_and_load
> > > File "", line 986, in _find_and_load_unlocked
> > > File "", line 680, in _load_unlocked
> > > File "", line 790, in exec_module
> > > File "", line 228, in _call_with_frames_removed File ".\bot.py", line 23, in nonebot.load_plugins("src/plugins") File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p ackages\nonebot\plugin__init__.py", line 1013, in load_plugins
> > > result = context.run(_load_plugin, manager, plugin_name)
> > > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > > ackages\nonebot\plugin__init__.py", line 960, in _load_plugin
> > > > module = manager.load_plugin(plugin_name)
> > > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
> > > > ackages\nonebot\plugin\manager.py", line 146, in load_plugin
> > > > return importlib.import_module(f"{self.namespace}.{name}")
> > > > File "c:\users\administrator\appdata\local\programs\python\python39\lib\import
> > > > lib__init__.py", line 127, in import_module
> > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > File "", line 1030, in _gcd_import
> > > > File "", line 1007, in _find_and_load
> > > > File "", line 986, in _find_and_load_unlocked
> > > > File "", line 680, in _load_unlocked
> > > > File "", line 790, in exec_module
> > > > File "", line 228, in _call_with_frames_removed
> > > > File "src/plugins\nonebot_plugin_gamedraw__init__.py", line 5, in
> > > > from .genshin_handle import genshin_draw, update_genshin_info, reset_count
> > > > File "src/plugins\nonebot_plugin_gamedraw\genshin_handle.py", line 5, in
> > > > from .update_game_info import update_info
> > > > File "src/plugins\nonebot_plugin_gamedraw\update_game_info.py", line 7, in
> > > > from .util import download_img
> > > > File "src/plugins\nonebot_plugin_gamedraw\util.py", line 10, in
> > > > import pypinyin
> > > > ModuleNotFoundError: No module named 'pypinyin'
> > 
> > 
> > 缺少pypinyin，直接pip install pypinyin
> 
> 请问方舟抽卡只有新干员up池没有轮换池吗

目前是根据明日方舟官方开启什么池子，抽卡也会自动爬取开启，未来可能会添加手动更换指定池子的功能，如果你希望目前就开启指定池子，可以在 data/draw_card/draw_card_up/prts_up_char.json中更改角色以及概率，并添加标题（标题必须要！！）和修改时间，时间结束日期必须要大于今天
