### ISSUE TITLE
碧蓝航线活动池抽卡错误？报错阈值在103和104之间

### ISSUE THREAD

**Issue by lkfun** [HibiKier/nonebot_plugin_gamedraw#76]
![image](https://user-images.githubusercontent.com/25656788/191077731-b197e13c-012e-4cbe-8ac8-060367526954.png)

**Comment by SoYeonQwQ** [comment]
好像是抽到彩船就报错了

**Comment by lkfun** [comment]
> 好像是抽到彩船就报错了

好像是的，我这儿的数组加了个彩，暂时能用了
https://github.com/HibiKier/nonebot_plugin_gamedraw/blob/aa30c6bf1caef9791071f72f4ec26aa68f43b105/draw_card/handles/azur_handle.py#L27

**Comment by SoYeonQwQ** [comment]
> 



> > 是抽到彩船就报错了
> 
> 好像是的，我这里的菜加了个彩，暂时可以用
> 
> https://github.com/HibiKier/nonebot_plugin_gamedraw/blob/aa30c6bf1caef9791071f72f4ec26aa68f43b105/draw_card/handles/azur_handle.py#L27



> > 好像是抽到彩船就报错了
> 
> 好像是的，我这儿的数组加了个彩，暂时能用了
> 
> https://github.com/HibiKier/nonebot_plugin_gamedraw/blob/aa30c6bf1caef9791071f72f4ec26aa68f43b105/draw_card/handles/azur_handle.py#L27

41行改成5，83行加一个5，85行增加self.config.AZUR_FIVE_P,

**Comment by 1717tian** [comment]
第83行数组加个5 self.config.AZUR_FIVE_P, 可以解决

**Comment by FantasyOwl** [comment]
上面的2个方法我都试了，还是出错

**Comment by 1717tian** [comment]
> 上面的2个方法我都试了，还是出错

在上面数组里加完彩 再在第83行数组 改为[5, 4, 3, 2, 1],
                [
                    self.config.AZUR_FIVE_P,
                    self.config.AZUR_FOUR_P,
                    self.config.AZUR_THREE_P,
                    self.config.AZUR_TWO_P,
                    self.config.AZUR_ONE_P,
                ],

**Comment by FantasyOwl** [comment]
>我是这样设置的，依旧出错了 

def star_str(self) -> str:
        return ["白", "蓝", "紫", "金","彩"][self.star - 1]

  if not acquire_char:
            star = self.get_star(
                [5,4, 3, 2, 1],
                [
		    self.config.AZUR_FIVE_P,
                    self.config.AZUR_FOUR_P,
                    self.config.AZUR_THREE_P,
                    self.config.AZUR_TWO_P,
                    self.config.AZUR_ONE_P,
                ],
            )

**Comment by 1717tian** [comment]
> 

我自己bot改完了倒是没报错过  看看报错

**Comment by 1717tian** [comment]
> > 我是这样设置的，依旧出错了
> 
> def star_str(self) -> str: return ["白", "蓝", "紫", "金","彩"][self.star - 1]
> 
> if not acquire_char: star = self.get_star( [5,4, 3, 2, 1], [ self.config.AZUR_FIVE_P, self.config.AZUR_FOUR_P, self.config.AZUR_THREE_P, self.config.AZUR_TWO_P, self.config.AZUR_ONE_P, ], )

我自己bot改完了倒是没报错过 看看报错

**Comment by FantasyOwl** [comment]
> > > 我是这样设置的，依旧出错了
> > 
> > 
> > def star_str(self) -> str: return ["白", "蓝", "紫", "金","彩"][self.star - 1]
> > if not acquire_char: star = self.get_star( [5,4, 3, 2, 1], [ self.config.AZUR_FIVE_P, self.config.AZUR_FOUR_P, self.config.AZUR_THREE_P, self.config.AZUR_TWO_P, self.config.AZUR_ONE_P, ], )
> 
> 我自己bot改完了倒是没报错过 看看报错

Event will be handled by <Matcher from nonebot_plugin_gamedraw, type=message, priority=5, temp=False>
10-13 16:27:23 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last):
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/__init__.py", line 97, in handler
    res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id)
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 102, in draw
    index2card = self.get_cards(count, **kwargs)
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in get_cards
    return [(self.get_card(**kwargs), i) for i in range(count)]
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in <listcomp>
    return [(self.get_card(**kwargs), i) for i in range(count)]
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 92, in get_card
    acquire_char = random.choice(
  File "/usr/local/Python-3.9.12/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by 1717tian** [comment]
> File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in get_cards
> return [(self.get_card(**kwargs), i) for i in range(count)]
> File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in
> return [(self.get_card(**kwargs), i) for i in range(count)]
> File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 92, in get_card
> acquire_char = random.choice(

你27行彩船加了嘛

**Comment by FantasyOwl** [comment]
> 

加了，刚刚上面回复的就是代码里的样子

**Comment by 1717tian** [comment]
> > 
> 
> 加了，刚刚上面回复的就是代码里的样子

5，后面加空格

**Comment by FantasyOwl** [comment]
> 

还是没用，报错好像是star往下传了个空值

**Comment by 1717tian** [comment]
> > 
> 
> 还是没用，报错好像是star往下传了个空值

你“彩”前是不是也没加空格

**Comment by FantasyOwl** [comment]
加了的，我都加了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午4:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/nonebot_plugin_gamedraw] 碧蓝航线活动池抽卡错误？报错阈值在103和104之间 (Issue #76)





    
还是没用，报错好像是star往下传了个空值
  
你“彩”前是不是也没加空格

**Comment by FantasyOwl** [comment]
> > > 
> > 
> > 
> > 还是没用，报错好像是star往下传了个空值
> 
> 你“彩”前是不是也没加空格

 Event will be handled by <Matcher from nonebot_plugin_gamedraw, type=message, priority=5, temp=False>
10-13 16:58:42 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last):
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/__init__.py", line 97, in handler
    res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id)
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 102, in draw
    index2card = self.get_cards(count, **kwargs)
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in get_cards
    return [(self.get_card(**kwargs), i) for i in range(count)]
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in <listcomp>
    return [(self.get_card(**kwargs), i) for i in range(count)]
  File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 92, in get_card
    acquire_char = random.choice(
  File "/usr/local/Python-3.9.12/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by 1717tian** [comment]
> e 102, in draw

又去看了下代码第41行 maxstar要改成5

**Comment by 1717tian** [comment]
> > > > 
> > > 
> > > 
> > > 还是没用，报错好像是star往下传了个空值
> > 
> > 
> > 你“彩”前是不是也没加空格
> 
> Event will be handled by <Matcher from nonebot_plugin_gamedraw, type=message, priority=5, temp=False> 10-13 16:58:42 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last): File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/**init**.py", line 97, in handler res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id) File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 102, in draw index2card = self.get_cards(count, **kwargs) File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in get_cards return [(self.get_card(**kwargs), i) for i in range(count)] File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in return [(self.get_card(**kwargs), i) for i in range(count)] File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 92, in get_card acquire_char = random.choice( File "/usr/local/Python-3.9.12/lib/python3.9/random.py", line 346, in choice return seq[self._randbelow(len(seq))] IndexError: list index out of range

又去看了下代码第41行 maxstar要改成5

**Comment by FantasyOwl** [comment]
self.max_star = 5


改了以后依旧报错


Event will be handled by <Matcher from nonebot_plugin_gamedraw, type=message, priority=5, temp=False&gt;
10-13 17:31:05 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last):
&nbsp; File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/__init__.py", line 97, in handler
&nbsp; &nbsp; res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id)
&nbsp; File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 102, in draw
&nbsp; &nbsp; index2card = self.get_cards(count, **kwargs)
&nbsp; File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in get_cards
&nbsp; &nbsp; return [(self.get_card(**kwargs), i) for i in range(count)]
&nbsp; File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in <listcomp&gt;
&nbsp; &nbsp; return [(self.get_card(**kwargs), i) for i in range(count)]
&nbsp; File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 92, in get_card
&nbsp; &nbsp; acquire_char = random.choice(
&nbsp; File "/usr/local/Python-3.9.12/lib/python3.9/random.py", line 346, in choice
&nbsp; &nbsp; return seq[self._randbelow(len(seq))]
IndexError: list index out of range







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月13日(星期四) 下午5:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HibiKier/nonebot_plugin_gamedraw] 碧蓝航线活动池抽卡错误？报错阈值在103和104之间 (Issue #76)





      
还是没用，报错好像是star往下传了个空值
  
你“彩”前是不是也没加空格
  
Event will be handled by <Matcher from nonebot_plugin_gamedraw, type=message, priority=5, temp=False&gt; 10-13 16:58:42 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last): File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/init.py", line 97, in handler res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id) File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 102, in draw index2card = self.get_cards(count, **kwargs) File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in get_cards return [(self.get_card(**kwargs), i) for i in range(count)] File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/base_handle.py", line 79, in return [(self.get_card(**kwargs), i) for i in range(count)] File "/usr/local/Python-3.9.12/lib/python3.9/site-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 92, in get_card acquire_char = random.choice( File "/usr/local/Python-3.9.12/lib/python3.9/random.py", line 346, in choice return seq[self._randbelow(len(seq))] IndexError: list index out of range
  
又去看了下代码第41行 maxstar要改成5
