### ISSUE TITLE
建议添加一个requirements

### ISSUE THREAD

**Issue by Nicotinamide** [HibiKier/nonebot_plugin_gamedraw#8]
我运行了好多次才集齐

**Comment by HibiKier** [comment]
ok，下次更新添加requirements

**Comment by Nicotinamide** [comment]
这个怎么解决啊
![0FFF41B80ECC870B309D9833A0202E3E.jpg](https://i.loli.net/2021/06/13/ANJi3sRgkvWuXPS.jpg)

**Comment by HibiKier** [comment]
删除azur.json重新更新

**Comment by HibiKier** [comment]
而且，你要安装nb2商店里的自动更新插件scheduler啊

**Comment by HibiKier** [comment]
还有nb2商店里的定时任务插件 scheduler https://v2.nonebot.dev/store.html

**Comment by Nicotinamide** [comment]
🆗
