### ISSUE TITLE
坎公骑冠剑 角色解析错误

### ISSUE THREAD

**Issue by stormspiritLiu** [HibiKier/nonebot_plugin_gamedraw#81]
应该改为
`                    name = char.xpath("./th[1]/a[1]/@title")[0]
                    avatar = char.xpath("./th[1]/a/img/@src")[0]
                    star = char.xpath("./th[1]/span/img/@alt")[0]`

guardian_handle.py   236line

**Comment by HibiKier** [comment]
cbe65571fe73151621d33da4f54684526402a33f
